name: "manylinux"
froms:
  - quay.io/pypa/manylinux_2_28_x86_64:2024-04-23-ef7507e
srcs:
  - ci/build/build-manylinux-forge.sh
build_args:
  - BUILDKITE_BAZEL_CACHE_URL
  - HOSTTYPE=x86_64
dockerfile: ci/docker/manylinux.Dockerfile
